from page_object.admin.AdminAddGroupPage import AdminAddGroupPage
from page_object.admin.AdminAddPeriodicTaskPage import AdminAddPeriodicTaskPage
from page_object.admin.AdminGroupsListPage import AdminGroupsListPage
from page_object.admin.AdminIngestPlansListPage import AdminIngestPlansListPage
from page_object.admin.AdminIngestResultsListPage import AdminIngestResultsListPage
from page_object.admin.AdminPeriodicTasksListPage import AdminPeriodicTasksListPage
from page_object.architect.ArchitectDashboardPage import ArchitectDashboardPage
from page_object.architect.ArchitectIngestPage import ArchitectIngestPage
from page_object.base_page import BasePage
from page_object.admin.AdminAddUserProfilePage import AdminAddUserProfilePage
from page_object.admin.AdminUserProfileListPage import AdminUserProfileListPage
from page_object.admin.AdminAddUserPage import AdminAddUserPage
from page_object.admin.AdminUsersListPage import AdminUsersListPage
from page_object.admin.AdminDashboardPage import AdminDashboardPage
from page_object.admin.AdminLoginPage import AdminLoginPage
from page_object.admin.AdminCollectionsListPage import AdminCollectionsListPage
from page_object.admin.AdminAddCollectionPage import AdminAddCollectionPage
from page_object.admin.AdminClustersListPage import AdminClustersListPage
from page_object.admin.AdminAddClusterPage import AdminAddClusterPage
from page_object.blueprint.BlueprintClusterDetailPage import BlueprintClusterDetailPage
from page_object.blueprint.BlueprintIngestedDetailPage import BlueprintIngestedDetailPage
from page_object.blueprint.BlueprintLoginPage import BlueprintLoginPage
from page_object.blueprint.BlueprintDashboardPage import BlueprintDashboardPage
from page_object.blueprint.BlueprintCollectionDetailPage import BlueprintCollectionDetailPage

# all global objects for pages
base_page = BasePage(None)
blueprint_login_page = BlueprintLoginPage(base_page)
blueprint_dashboard_page = BlueprintDashboardPage(base_page)
blueprint_ingested_document_page = BlueprintIngestedDetailPage(base_page)
blueprint_collection_details_page = BlueprintCollectionDetailPage(base_page)
blueprint_cluster_details_page = BlueprintClusterDetailPage(base_page)
architect_dashboard_page = ArchitectDashboardPage(base_page)
architect_ingest_page = ArchitectIngestPage(base_page)

admin_login_page = AdminLoginPage(base_page)
admin_dashboard_page = AdminDashboardPage(base_page)
admin_user_list_page = AdminUsersListPage(base_page)
admin_add_user_page = AdminAddUserPage(base_page)
admin_user_profile_page = AdminUserProfileListPage(base_page)
admin_add_user_profile_page = AdminAddUserProfilePage(base_page)
admin_collection_list_page = AdminCollectionsListPage(base_page)
admin_add_collection_page = AdminAddCollectionPage(base_page)
admin_cluster_list_page = AdminClustersListPage(base_page)
admin_add_cluster_page = AdminAddClusterPage(base_page)
admin_ingest_plans_list_page = AdminIngestPlansListPage(base_page)
admin_ingest_result_list_page = AdminIngestResultsListPage(base_page)
admin_group_list_page = AdminGroupsListPage(base_page)
admin_add_group_page = AdminAddGroupPage(base_page)
admin_periodic_task_list_page = AdminPeriodicTasksListPage(base_page)
admin_add_periodic_task_page = AdminAddPeriodicTaskPage(base_page)
